# Generated by Django 4.2.6 on 2023-10-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='vkr_project.content')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_audio', models.CharField(max_length=255)),
                ('creator_audio', models.CharField(max_length=255)),
                ('data_create', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='vkr_project.content')),
                ('video_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='vkr_project.videofiles')),
            ],
        ),
    ]
